FROM  openjdk:8-jre
# 挂载目录
VOLUME /temp

# 将jar包添加到容器中并更名为bidding-programme.jar
ADD ruoyi-admin.jar ruoyi-admin.jar

# 运行jar包
RUN bash -c 'touch ruoyi-admin.jar'

ENTRYPOINT ["java","-jar","ruoyi-admin.jar"]

EXPOSE 8082
